### ISSUE TITLE
Create common data-structures for pi, beacon,dongle (particularly download)

### ISSUE THREAD

**Issue by rlnsy** [ubc-systopia/pancast-code#27]

**Comment by aasthakm** [comment]
Fixed in the commits:
- https://github.com/ubc-systopia/pancast-code/commit/8f4f5f951eee033b5155148cb75f797fbc25b1d8
- https://github.com/ubc-systopia/pancast-code/commit/7eadc4c1b03aea62ddd1c04794d3f49dbccdcaae
- https://github.com/ubc-systopia/pancast-code/commit/62819e5bc87836a115d92326640f28aab0764bf5
